name: Publish Package to NPM

on:
  workflow_call:      # Triggered by release workflow
  workflow_dispatch:  # Can also be triggered manually

permissions:
  id-token: write  # Required for OIDC
  contents: read   # To checkout the code

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install -w --frozen-lockfile --filter={./vendor/*}

      - name: Sync license files
        run: pnpm tsx ./scripts/node/sync-licenses.ts

      - name: Publish to NPM registry
        id: changesets
        uses: changesets/action@v1
        env: # GITHUB_TOKEN is required by Changesets action to create GitHub Releases (which we don't need here, but the action requires it)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: pnpm publish:ci
          createGithubReleases: false
