name: Release

# Github Packages/Organization: "@mirasaki-oss"
# NPM Scope/Organization: "@md-oss"

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

env:
  CI: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write
  id-token: write # Required for OIDC (npm trusted publishing)
  pull-requests: write # Note: Requires "Allow GitHub Actions to create and approve pull requests" for user account / organization
  # Note: Publishing (with `commit`) requires "Workflows have read and write permissions in the repository for all scopes."
  # Note: If you're getting a write_package error, check https://github.com/orgs/YOUR_ORG/packages permissions.

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
          # registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Configure .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
            @mirasaki-oss:registry=https://npm.pkg.github.com/
            @md-oss:registry=https://registry.npmjs.org/
          EOF

      - name: Replace `@md-oss` with `@mirasaki-oss` across vendor (Github Packages)
        run: |
          pnpm exec tsx ./scripts/node/replace-scope.ts --scopeOld="@md-oss" --scopeNew="@mirasaki-oss" --paths="./.changeset/*,./apps,./packages,./vendor"

      - name: Install dependencies (Github Packages)
        run: pnpm install -w --no-frozen-lockfile --filter={./vendor/*}
        # Note: Using `--no-frozen-lockfile` here to allow updating lockfile for Github scope change

      # - name: Install dependencies (NPM)
      #   run: pnpm install -w --frozen-lockfile --filter={./vendor/*}

      - name: Sync license files
        run: pnpm tsx ./scripts/node/sync-licenses.ts

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm publish:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
